'use strict';
const STORAGE_KEY='control_presupuesto_v1';
const APP_VERSION=4;
const DEFAULT_CATEGORY_NAMES=['Alimentación','Transporte local','Bebidas / antojos','Trabajo / estudios','Salud','Higiene / limpieza','Trámites / bancos','Alquiler / vivienda','Uniformes / accesorios','Comunicación','Viajes y traslados','Otros'];
const FREQUENT_DEFAULTS=['Alimentación','Transporte local','Bebidas / antojos','Trabajo / estudios','Salud','Higiene / limpieza'];
const DEFAULT_FAVORITES=[{label:'Micro',amount:2.5,category:'Transporte local'},{label:'Taxi',amount:10,category:'Transporte local'},{label:'Almuerzo',amount:20,category:'Alimentación'},{label:'Gaseosa',amount:5,category:'Bebidas / antojos'}];
const $=id=>document.getElementById(id);
const modalIds=['settingsModal','categoriesModal','categoryPickerModal','favoriteConfirmModal','favoriteEditorModal','expenseEditorModal','projectEditorModal'];
let selectedFavoriteId=null,editingFavoriteId=null,editingExpenseId=null,editingProjectId=null,lastAddedExpenseId=null,toastTimer=null,manualDate=false;
let state=loadState();

function uid(){return globalThis.crypto?.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function pad(n){return String(n).padStart(2,'0')}
function localDateKey(d=new Date()){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function localTimeKey(d=new Date()){return `${pad(d.getHours())}:${pad(d.getMinutes())}`}
function monthKey(d=new Date()){return localDateKey(d).slice(0,7)}
function localDateTime(date,time){const d=date||localDateKey(),t=time||localTimeKey();return `${d}T${t}:00`}
function parseAmount(v){const n=Number(String(v??'').trim().replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)?n:0}
function inputAmount(n){return n?String(Number(n)).replace('.',','):''}
function money(n){return `Bs ${new Intl.NumberFormat('es-BO',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)}`}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function monthLabel(k){const [y,m]=k.split('-').map(Number);return new Intl.DateTimeFormat('es-BO',{month:'long',year:'numeric'}).format(new Date(y,m-1,1))}
function categoryObject(name,index=0){return {id:uid(),name,hidden:false,order:index}}
function initialState(){return {version:APP_VERSION,expenses:[],categories:DEFAULT_CATEGORY_NAMES.map(categoryObject),favorites:DEFAULT_FAVORITES.map(f=>({id:uid(),...f})),monthSettings:{},projects:[{id:'general',name:'Gastos generales',budget:0,active:true}],recentCategories:[]}}
function migrateState(saved){const base=initialState(),s=saved&&typeof saved==='object'?saved:base;s.expenses=Array.isArray(s.expenses)?s.expenses:[];if(Array.isArray(s.categories)&&typeof s.categories[0]==='string')s.categories=s.categories.map(categoryObject);if(!Array.isArray(s.categories)||!s.categories.length)s.categories=base.categories;s.categories=s.categories.map((c,i)=>typeof c==='string'?categoryObject(c,i):{id:c.id||uid(),name:c.name||`Categoría ${i+1}`,hidden:!!c.hidden,order:Number.isFinite(c.order)?c.order:i});if(!s.categories.some(c=>c.name==='Otros'))s.categories.push(categoryObject('Otros',s.categories.length));s.favorites=(Array.isArray(s.favorites)?s.favorites:base.favorites).map(f=>({id:f.id||uid(),label:f.label||'Favorito',amount:Number(f.amount)||0,category:f.category||'Otros'}));s.projects=Array.isArray(s.projects)&&s.projects.length?s.projects:base.projects;if(!s.projects.some(p=>p.id==='general'))s.projects.unshift({id:'general',name:'Gastos generales',budget:0,active:true});if(!s.projects.some(p=>p.active))s.projects[0].active=true;s.monthSettings=s.monthSettings&&typeof s.monthSettings==='object'?s.monthSettings:{};if(s.settings&&!s.monthSettings[monthKey()])s.monthSettings[monthKey()]={budget:Number(s.settings.monthlyBudget)||0,savingsGoal:Number(s.settings.savingsGoal)||0};s.recentCategories=Array.isArray(s.recentCategories)?s.recentCategories:[];s.expenses=s.expenses.map(e=>{const created=e.createdAt||localDateTime(e.date||localDateKey(),'12:00');return{id:e.id||uid(),amount:Number(e.amount)||0,category:e.category||'Otros',detail:e.detail||'',projectId:e.projectId||'general',date:e.date||created.slice(0,10),createdAt:created}});s.version=APP_VERSION;return s}
function loadState(){try{return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'))}catch(e){console.error(e);return initialState()}}
function persist(render=true){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(render)renderAll()}
function sum(a){return a.reduce((t,x)=>t+Number(x.amount||0),0)}
function visibleCategories(){return state.categories.filter(c=>!c.hidden).sort((a,b)=>a.order-b.order)}
function categoryNames(){return visibleCategories().map(c=>c.name)}
function startOfWeek(d=new Date()){const x=new Date(d),o=(x.getDay()+6)%7;x.setDate(x.getDate()-o);x.setHours(0,0,0,0);return x}
function inThisWeek(date){const d=new Date(`${date}T12:00:00`),n=new Date();return d>=startOfWeek(n)&&d<=n}
function currentPeriodExpenses(period){const t=localDateKey(),m=monthKey();return state.expenses.filter(e=>period==='day'?e.date===t:period==='week'?inThisWeek(e.date):e.date.slice(0,7)===m)}
function activeProject(){return state.projects.find(p=>p.active)||state.projects[0]}
function projectById(id){return state.projects.find(p=>p.id===id)||state.projects.find(p=>p.id==='general')}
function getMonthSetting(k=monthKey()){const x=state.monthSettings[k]||{};return{budget:Number(x.budget)||0,savingsGoal:Number(x.savingsGoal)||0}}
function showToast(message,undo=false){const t=$('toast');t.innerHTML=undo?`${escapeHtml(message)} <button id="undoToastBtn" type="button">Deshacer</button>`:escapeHtml(message);t.hidden=false;clearTimeout(toastTimer);if(undo)$('undoToastBtn').onclick=undoLastExpense;toastTimer=setTimeout(()=>t.hidden=true,undo?5000:2500)}
function openModal(id){$(id).hidden=false;document.body.classList.add('modal-open')}
function closeModal(id){$(id).hidden=true;if(!modalIds.some(x=>!$(x).hidden))document.body.classList.remove('modal-open')}
function setSelectOptions(el,items,value){el.innerHTML=items.map(i=>`<option value="${escapeHtml(i.value)}">${escapeHtml(i.label)}</option>`).join('');if(value&&items.some(i=>i.value===value))el.value=value}
function registerRecentCategory(name){state.recentCategories=[name,...state.recentCategories.filter(x=>x!==name)].slice(0,4)}
function addExpense(amountValue,category,detail='',projectId='general',date=null,time=null){const amount=parseAmount(amountValue);if(amount<=0){showToast('Ingresa un monto válido.');return false}const chosen=category||categoryNames()[0]||'Otros';const now=new Date(),d=date||localDateKey(now),t=time||localTimeKey(now);const expense={id:uid(),amount,category:chosen,detail:detail.trim(),projectId:projectId||'general',date:d,createdAt:localDateTime(d,t)};state.expenses.push(expense);registerRecentCategory(chosen);lastAddedExpenseId=expense.id;persist();showToast('Gasto guardado correctamente.',true);return true}
function undoLastExpense(){if(!lastAddedExpenseId)return;state.expenses=state.expenses.filter(e=>e.id!==lastAddedExpenseId);lastAddedExpenseId=null;persist();$('toast').hidden=true;showToast('Registro deshecho.')}

function renderAll(){renderSelectors();renderTotals();renderActiveProject();renderFavorites();renderRecent();renderSummary();renderHistoryOptions();renderHistory();renderProjects();renderCategories();updateAutoDatePreview()}
function renderSelectors(){const cats=categoryNames(),projects=state.projects.map(p=>({value:p.id,label:p.active&&p.id!=='general'?`${p.name} (activo)`:p.name}));if(!$('categoryInput').value||!cats.includes($('categoryInput').value)){$('categoryInput').value=cats[0]||'Otros';$('categoryPickerText').textContent=cats[0]||'Otros'}setSelectOptions($('projectInput'),projects,activeProject().id);setSelectOptions($('favoriteConfirmProject'),projects,activeProject().id);setSelectOptions($('favoriteCategoryInput'),cats.map(x=>({value:x,label:x})),$('favoriteCategoryInput').value);setSelectOptions($('editExpenseCategory'),cats.map(x=>({value:x,label:x})),$('editExpenseCategory').value);setSelectOptions($('editExpenseProject'),projects,$('editExpenseProject').value)}
function renderTotals(){const now=new Date(),today=sum(currentPeriodExpenses('day')),week=sum(currentPeriodExpenses('week')),monthExpenses=currentPeriodExpenses('month'),month=sum(monthExpenses),cfg=getMonthSetting(),usable=Math.max(0,cfg.budget-cfg.savingsGoal),available=usable-month,daysInMonth=new Date(now.getFullYear(),now.getMonth()+1,0).getDate(),remainingDays=Math.max(1,daysInMonth-now.getDate()+1),daily=available/remainingDays,percent=usable>0?Math.min(100,month/usable*100):0;$('todayTotal').textContent=money(today);$('weekTotal').textContent=money(week);$('monthTotal').textContent=money(month);$('currentMonthName').textContent=monthLabel(monthKey());$('availableMonth').textContent=money(available);$('monthProgressBar').style.width=`${percent}%`;if(cfg.budget<=0){$('budgetStatus').textContent='Configura tu presupuesto mensual.';$('monthProgressBadge').textContent='Sin configurar';$('monthProgressBadge').className='badge';$('dailyAllowance').textContent='—';$('monthDaysInfo').textContent=`Este mes tiene ${daysInMonth} días.`}else{$('budgetStatus').textContent=`Presupuesto utilizable: ${money(usable)} · Ahorro: ${money(cfg.savingsGoal)}`;$('dailyAllowance').textContent=money(Math.max(0,daily));$('monthDaysInfo').textContent=`Referencia para ${remainingDays} día${remainingDays===1?'':'s'} restante${remainingDays===1?'':'s'} de ${daysInMonth}.`;const badge=$('monthProgressBadge');badge.textContent=`${Math.round(percent)}% usado`;badge.className=`badge ${percent>=100?'danger':percent>=75?'warning':'good'}`}$('paceMessage').textContent=cfg.budget<=0?'Configura tu presupuesto para ver el ritmo de gasto.':available<0?`Has superado tu monto utilizable en ${money(Math.abs(available))}.`:`Te quedan ${money(available)}. Para mantenerte dentro del presupuesto, la referencia es ${money(Math.max(0,daily))} por día.`}
function renderActiveProject(){const p=activeProject(),card=$('activeProjectCard');$('activeProjectLabel').textContent=p.name;if(p.id==='general'){card.hidden=true;return}card.hidden=false;const spent=sum(state.expenses.filter(e=>e.projectId===p.id)),avail=Number(p.budget||0)-spent,percent=p.budget>0?Math.min(100,spent/p.budget*100):0;$('activeProjectName').textContent=p.name;$('activeProjectBudget').textContent=money(p.budget);$('activeProjectSpent').textContent=money(spent);$('activeProjectAvailable').textContent=money(avail);$('activeProjectProgress').style.width=`${percent}%`;const hint=$('projectHint');hint.textContent=`El gasto se asignará a “${p.name}” y también contará en el total mensual.`}
function renderRecent(){const valid=state.recentCategories.filter(n=>categoryNames().includes(n)).slice(0,4);$('recentSection').hidden=!valid.length;$('recentCategories').innerHTML=valid.map(n=>`<button type="button" data-recent="${escapeHtml(n)}">${escapeHtml(n)}</button>`).join('');$('recentCategories').querySelectorAll('[data-recent]').forEach(b=>b.onclick=()=>{$('categoryInput').value=b.dataset.recent;$('categoryPickerText').textContent=b.dataset.recent;window.scrollTo({top:$('expenseForm').offsetTop-80,behavior:'smooth'});$('amountInput').focus()})}
function renderFavorites(){$('quickButtons').innerHTML=state.favorites.length?state.favorites.map(f=>`<article class="quick-card"><button class="quick-use" data-favorite="${f.id}" type="button"><strong>${escapeHtml(f.label)}</strong><span>${money(f.amount)} · ${escapeHtml(f.category)}</span></button><button class="quick-edit" data-edit-favorite="${f.id}" type="button">✎</button></article>`).join(''):'<p class="empty">Aún no tienes favoritos.</p>';$('quickButtons').querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>openFavoriteConfirmation(b.dataset.favorite));$('quickButtons').querySelectorAll('[data-edit-favorite]').forEach(b=>b.onclick=e=>{e.stopPropagation();openFavoriteEditor(b.dataset.editFavorite)})}
function openFavoriteConfirmation(id){const f=state.favorites.find(x=>x.id===id);if(!f)return;selectedFavoriteId=id;$('favoriteConfirmTitle').textContent=`Registrar ${f.label}`;$('favoriteConfirmInfo').textContent=`Categoría: ${f.category}. Revisa el monto antes de confirmar.`;$('favoriteConfirmAmount').value=inputAmount(f.amount);renderSelectors();openModal('favoriteConfirmModal');setTimeout(()=>$('favoriteConfirmAmount').focus(),50)}
function openFavoriteEditor(id=null){editingFavoriteId=id;const f=state.favorites.find(x=>x.id===id);$('favoriteEditorTitle').textContent=f?'Editar favorito':'Nuevo favorito';$('favoriteLabelInput').value=f?.label||'';$('favoriteAmountInput').value=inputAmount(f?.amount||0);renderSelectors();$('favoriteCategoryInput').value=f?.category||categoryNames()[0];$('deleteFavoriteBtn').hidden=!f;openModal('favoriteEditorModal')}
function renderSummary(){const period=$('periodFilter').value||'month',rows=currentPeriodExpenses(period),total=sum(rows),group={};rows.forEach(e=>group[e.category]=(group[e.category]||0)+e.amount);$('categoryPeriodTotal').textContent=`Total: ${money(total)}`;const sorted=Object.entries(group).sort((a,b)=>b[1]-a[1]);$('categorySummary').innerHTML=sorted.length?sorted.map(([name,value])=>`<div class="bar-row"><div class="bar-info"><span>${escapeHtml(name)}</span><strong>${money(value)}</strong></div><div class="bar-bg"><div class="bar-fill" style="width:${total?value/total*100:0}%"></div></div></div>`).join(''):'<p class="empty">No hay gastos en este periodo.</p>'}
function historyMonths(){return [...new Set(state.expenses.map(e=>e.date.slice(0,7)))].sort().reverse()}
function renderHistoryOptions(){const current=$('historyMonthFilter').value||monthKey(),items=[{value:'all',label:'Todos los meses'},...historyMonths().map(k=>({value:k,label:monthLabel(k)}))];setSelectOptions($('historyMonthFilter'),items,items.some(x=>x.value===current)?current:'all')}
function renderHistory(){const q=$('searchInput').value.trim().toLowerCase(),m=$('historyMonthFilter').value||'all',rows=state.expenses.filter(e=>(m==='all'||e.date.startsWith(m))&&(!q||`${e.category} ${e.detail} ${projectById(e.projectId)?.name}`.toLowerCase().includes(q))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));$('historyList').innerHTML=rows.length?rows.map(e=>{const dt=new Date(e.createdAt),time=Number.isNaN(dt.getTime())?'':dt.toLocaleTimeString('es-BO',{hour:'2-digit',minute:'2-digit'});return`<article class="item"><div><strong>${escapeHtml(e.detail||e.category)}</strong><small>${escapeHtml(e.category)} · ${e.date} ${time} · ${escapeHtml(projectById(e.projectId)?.name||'General')}</small></div><div class="amount-block"><strong>${money(e.amount)}</strong><div class="item-actions"><button class="mini-btn" data-edit-expense="${e.id}" type="button">Editar</button><button class="mini-btn delete" data-delete-expense="${e.id}" type="button">Borrar</button></div></div></article>`}).join(''):'<p class="empty">No hay gastos para mostrar.</p>';$('historyList').querySelectorAll('[data-edit-expense]').forEach(b=>b.onclick=()=>openExpenseEditor(b.dataset.editExpense));$('historyList').querySelectorAll('[data-delete-expense]').forEach(b=>b.onclick=()=>{if(confirm('¿Borrar este gasto?')){state.expenses=state.expenses.filter(e=>e.id!==b.dataset.deleteExpense);persist();showToast('Gasto borrado.')}})}
function openExpenseEditor(id){const e=state.expenses.find(x=>x.id===id);if(!e)return;editingExpenseId=id;renderSelectors();$('editExpenseAmount').value=inputAmount(e.amount);$('editExpenseCategory').value=e.category;$('editExpenseDetail').value=e.detail;$('editExpenseProject').value=e.projectId;$('editExpenseDate').value=e.date;$('editExpenseTime').value=e.createdAt.slice(11,16);openModal('expenseEditorModal')}
function renderProjects(){$('projectList').innerHTML=state.projects.filter(p=>p.id!=='general').map(p=>{const spent=sum(state.expenses.filter(e=>e.projectId===p.id));return`<article class="item"><div><strong>${escapeHtml(p.name)} ${p.active?'· Activo':''}</strong><small>Presupuesto ${money(p.budget)} · Gastado ${money(spent)} · Disponible ${money(Number(p.budget||0)-spent)}</small></div><div class="project-actions">${p.active?'':`<button class="mini-btn" data-activate-project="${p.id}" type="button">Activar</button>`}<button class="mini-btn" data-edit-project="${p.id}" type="button">Editar</button></div></article>`}).join('')||'<p class="empty">No hay proyectos creados.</p>';$('projectList').querySelectorAll('[data-activate-project]').forEach(b=>b.onclick=()=>activateProject(b.dataset.activateProject));$('projectList').querySelectorAll('[data-edit-project]').forEach(b=>b.onclick=()=>openProjectEditor(b.dataset.editProject))}
function activateProject(id){state.projects.forEach(p=>p.active=p.id===id);persist();showToast(`Proyecto activo: ${projectById(id).name}`);window.scrollTo({top:0,behavior:'smooth'})}
function openProjectEditor(id){const p=projectById(id);editingProjectId=id;$('editProjectName').value=p.name;$('editProjectBudget').value=inputAmount(p.budget);openModal('projectEditorModal')}
function renderCategories(){const rows=[...state.categories].sort((a,b)=>a.order-b.order);$('categoriesList').innerHTML=rows.map((c,i)=>`<div class="category-item ${c.hidden?'is-hidden':''}"><span>${escapeHtml(c.name)}${c.hidden?' · Oculta':''}</span><div class="category-actions"><button class="mini-btn" data-up-category="${c.id}" type="button" ${i===0?'disabled':''}>↑</button><button class="mini-btn" data-down-category="${c.id}" type="button" ${i===rows.length-1?'disabled':''}>↓</button><button class="mini-btn" data-rename-category="${c.id}" type="button">Editar</button><button class="mini-btn" data-toggle-category="${c.id}" type="button" ${c.name==='Otros'?'disabled':''}>${c.hidden?'Mostrar':'Ocultar'}</button></div></div>`).join('');$('categoriesList').querySelectorAll('[data-up-category]').forEach(b=>b.onclick=()=>moveCategory(b.dataset.upCategory,-1));$('categoriesList').querySelectorAll('[data-down-category]').forEach(b=>b.onclick=()=>moveCategory(b.dataset.downCategory,1));$('categoriesList').querySelectorAll('[data-rename-category]').forEach(b=>b.onclick=()=>renameCategory(b.dataset.renameCategory));$('categoriesList').querySelectorAll('[data-toggle-category]').forEach(b=>b.onclick=()=>toggleCategory(b.dataset.toggleCategory))}
function moveCategory(id,delta){const rows=[...state.categories].sort((a,b)=>a.order-b.order),i=rows.findIndex(c=>c.id===id),j=i+delta;if(i<0||j<0||j>=rows.length)return;[rows[i].order,rows[j].order]=[rows[j].order,rows[i].order];persist();showToast('Orden actualizado.')}
function renameCategory(id){const c=state.categories.find(x=>x.id===id),name=prompt('Nuevo nombre:',c.name)?.trim();if(!name||name===c.name)return;if(state.categories.some(x=>x.name.toLowerCase()===name.toLowerCase())){showToast('Esa categoría ya existe.');return}const old=c.name;c.name=name;state.expenses.forEach(e=>{if(e.category===old)e.category=name});state.favorites.forEach(f=>{if(f.category===old)f.category=name});state.recentCategories=state.recentCategories.map(x=>x===old?name:x);persist();showToast('Categoría actualizada.')}
function toggleCategory(id){const c=state.categories.find(x=>x.id===id);if(!c||c.name==='Otros')return;c.hidden=!c.hidden;persist();showToast(c.hidden?'Categoría ocultada.':'Categoría visible.')}
function renderCategoryPicker(){const selected=$('categoryInput').value,visible=visibleCategories(),frequent=visible.filter(c=>FREQUENT_DEFAULTS.includes(c.name)).slice(0,6),all=visible.filter(c=>!frequent.some(f=>f.id===c.id));const html=c=>`<button class="category-option ${c.name===selected?'selected':''}" data-category-option="${escapeHtml(c.name)}" type="button">${escapeHtml(c.name)}</button>`;$('frequentCategoryOptions').innerHTML=frequent.map(html).join('')||'<span class="empty">Sin categorías frecuentes.</span>';$('categoryOptions').innerHTML=all.map(html).join('');document.querySelectorAll('[data-category-option]').forEach(b=>b.onclick=()=>{$('categoryInput').value=b.dataset.categoryOption;$('categoryPickerText').textContent=b.dataset.categoryOption;closeModal('categoryPickerModal');renderCategoryPicker()})}
function loadSettingsMonth(){const k=$('settingsMonthInput').value||monthKey(),c=getMonthSetting(k);$('monthlyBudgetInput').value=inputAmount(c.budget);$('savingsGoalInput').value=inputAmount(c.savingsGoal)}
function exportCsv(){const m=$('historyMonthFilter').value||'all',rows=(m==='all'?state.expenses:state.expenses.filter(e=>e.date.startsWith(m))).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));if(!rows.length){showToast('No hay gastos para exportar.');return}const data=[['Mes','Fecha','Hora','Categoría','Detalle','Monto Bs','Proyecto'],...rows.map(e=>[e.date.slice(0,7),e.date,e.createdAt.slice(11,16),e.category,e.detail,Number(e.amount).toFixed(2).replace('.',','),projectById(e.projectId)?.name||'General'])];downloadBlob('\uFEFF'+data.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\r\n'),'text/csv;charset=utf-8',`control-presupuesto-${m}.csv`);showToast('Archivo compatible con Excel creado.')}
function downloadBlob(content,type,name){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function exportBackup(){downloadBlob(JSON.stringify({app:'Control de Presupuesto',version:APP_VERSION,exportedAt:new Date().toISOString(),data:state},null,2),'application/json',`respaldo-presupuesto-${localDateKey()}.json`);showToast('Copia de seguridad creada.')}
function importBackup(file){const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result),data=parsed.data||parsed;if(!data.expenses||!data.categories)throw new Error('Formato inválido');if(!confirm('La copia reemplazará los datos actuales. ¿Continuar?'))return;state=migrateState(data);persist();closeModal('settingsModal');showToast('Copia importada correctamente.')}catch(e){showToast('No se pudo importar el archivo.')}};reader.readAsText(file)}
function updateAutoDatePreview(){if(manualDate)return;const now=new Date();$('autoDatePreview').textContent=`Automática: ${now.toLocaleDateString('es-BO')} · ${now.toLocaleTimeString('es-BO',{hour:'2-digit',minute:'2-digit'})}`}
function resetDateMode(){manualDate=false;$('manualDateFields').hidden=true;$('toggleDateBtn').textContent='Cambiar fecha';updateAutoDatePreview()}
async function checkForUpdate(){showToast('Buscando actualización…');if(!navigator.serviceWorker){showToast('La actualización automática no está disponible aquí.');return}const reg=await navigator.serviceWorker.getRegistration();if(!reg){showToast('Servicio de actualización no registrado.');return}await reg.update();if(reg.waiting){reg.waiting.postMessage({type:'SKIP_WAITING'});showToast('Actualización encontrada. Se aplicará ahora.')}else showToast('Ya tienes la versión más reciente.')}

$('expenseForm').onsubmit=e=>{e.preventDefault();const ok=addExpense($('amountInput').value,$('categoryInput').value,$('detailInput').value,$('projectInput').value,manualDate?$('expenseDateInput').value:null,manualDate?$('expenseTimeInput').value:null);if(ok){$('amountInput').value='';$('detailInput').value='';resetDateMode();$('amountInput').focus()}};
$('toggleDateBtn').onclick=()=>{manualDate=!manualDate;$('manualDateFields').hidden=!manualDate;$('toggleDateBtn').textContent=manualDate?'Usar automática':'Cambiar fecha';if(manualDate){$('expenseDateInput').value=localDateKey();$('expenseTimeInput').value=localTimeKey();$('autoDatePreview').textContent='Selecciona la fecha y hora del gasto.'}else updateAutoDatePreview()};
$('categoryPickerBtn').onclick=()=>{renderCategoryPicker();openModal('categoryPickerModal')};$('periodFilter').onchange=renderSummary;$('searchInput').oninput=renderHistory;$('historyMonthFilter').onchange=renderHistory;$('exportBtn').onclick=exportCsv;
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(`${t.dataset.tab}Tab`).classList.add('active')});
$('settingsBtn').onclick=()=>{$('settingsMonthInput').value=monthKey();loadSettingsMonth();openModal('settingsModal')};$('settingsMonthInput').onchange=loadSettingsMonth;$('saveSettingsBtn').onclick=()=>{const k=$('settingsMonthInput').value||monthKey();state.monthSettings[k]={budget:parseAmount($('monthlyBudgetInput').value),savingsGoal:parseAmount($('savingsGoalInput').value)};persist();closeModal('settingsModal');showToast(`Presupuesto guardado para ${monthLabel(k)}.`)};
$('openCategoriesBtn').onclick=()=>{closeModal('settingsModal');openModal('categoriesModal')};$('addCategoryBtn').onclick=()=>{const n=$('newCategoryInput').value.trim();if(!n)return;if(state.categories.some(c=>c.name.toLowerCase()===n.toLowerCase())){showToast('Esa categoría ya existe.');return}state.categories.push(categoryObject(n,state.categories.length));$('newCategoryInput').value='';persist();showToast('Categoría agregada.')};
$('backupBtn').onclick=exportBackup;$('importBtn').onclick=()=>$('importFileInput').click();$('importFileInput').onchange=e=>{if(e.target.files[0])importBackup(e.target.files[0]);e.target.value=''};$('resetBtn').onclick=()=>{if(confirm('Se borrarán todos los datos de este dispositivo. ¿Continuar?')){state=initialState();persist();closeModal('settingsModal');showToast('Todos los datos fueron borrados.')}};
$('addFavoriteBtn').onclick=()=>openFavoriteEditor();$('confirmFavoriteBtn').onclick=()=>{const f=state.favorites.find(x=>x.id===selectedFavoriteId);if(f&&addExpense($('favoriteConfirmAmount').value,f.category,f.label,$('favoriteConfirmProject').value)){closeModal('favoriteConfirmModal')}};$('saveFavoriteBtn').onclick=()=>{const label=$('favoriteLabelInput').value.trim(),amount=parseAmount($('favoriteAmountInput').value),category=$('favoriteCategoryInput').value;if(!label||amount<=0){showToast('Completa nombre y monto válido.');return}if(editingFavoriteId){const f=state.favorites.find(x=>x.id===editingFavoriteId);Object.assign(f,{label,amount,category})}else state.favorites.push({id:uid(),label,amount,category});persist();closeModal('favoriteEditorModal');showToast('Favorito guardado.')};$('deleteFavoriteBtn').onclick=()=>{if(editingFavoriteId&&confirm('¿Borrar este favorito?')){state.favorites=state.favorites.filter(f=>f.id!==editingFavoriteId);persist();closeModal('favoriteEditorModal');showToast('Favorito borrado.')}};
$('saveExpenseEditBtn').onclick=()=>{const e=state.expenses.find(x=>x.id===editingExpenseId),amount=parseAmount($('editExpenseAmount').value);if(!e||amount<=0){showToast('Monto inválido.');return}e.amount=amount;e.category=$('editExpenseCategory').value;e.detail=$('editExpenseDetail').value.trim();e.projectId=$('editExpenseProject').value;e.date=$('editExpenseDate').value;e.createdAt=localDateTime(e.date,$('editExpenseTime').value||'12:00');registerRecentCategory(e.category);persist();closeModal('expenseEditorModal');showToast('Gasto actualizado.')};
$('projectForm').onsubmit=e=>{e.preventDefault();const name=$('projectNameInput').value.trim();if(!name)return;state.projects.forEach(p=>p.active=false);state.projects.push({id:uid(),name,budget:parseAmount($('projectBudgetInput').value),active:true});$('projectNameInput').value='';$('projectBudgetInput').value='';persist();showToast(`Proyecto activo: ${name}`);window.scrollTo({top:0,behavior:'smooth'})};$('finishProjectBtn').onclick=()=>activateProject('general');$('saveProjectEditBtn').onclick=()=>{const p=state.projects.find(x=>x.id===editingProjectId),name=$('editProjectName').value.trim();if(!p||!name)return;p.name=name;p.budget=parseAmount($('editProjectBudget').value);persist();closeModal('projectEditorModal');showToast('Proyecto actualizado.')};
$('checkUpdateBtn').onclick=checkForUpdate;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));modalIds.forEach(id=>$(id).onclick=e=>{if(e.target===$(id))closeModal(id)});document.onkeydown=e=>{if(e.key==='Escape'){const open=[...modalIds].reverse().find(id=>!$(id).hidden);if(open)closeModal(open)}};
function registerServiceWorker(){if(!('serviceWorker'in navigator))return;let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!reloading){reloading=true;location.reload()}});navigator.serviceWorker.register('./sw.js?v=4').then(reg=>{reg.update();if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'})}).catch(console.warn)}
renderAll();setInterval(updateAutoDatePreview,30000);registerServiceWorker();
